# Generated by Django 5.2.9 on 2026-01-26 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_categorydb_menuitemdb_remove_menuitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Cooking', 'Cooking'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('Total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Note', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.menuitemdb')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurantapp.orderdb')),
            ],
        ),
        migrations.AddField(
            model_name='orderdb',
            name='Table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.tabledb'),
        ),
    ]
